Продемонстрируйте работу с классом, с основными методами, операторами. Программа не обязательно должна взаимодействовать с пользователем, главная цель — показать пример использования класса.

    Статические объекты - х
    Динамическое создание объекта - х
    Создайте массив из объектов. Обратитесь к объектам, вызовите метод(ы). Когда здесь вызываются конструкторы?
    Создайте динамический массив из объектов. Обратитесь к объектам, вызовите метод(ы). Когда здесь вызываются конструкторы? - x 
    Создать массив из указателей на объекты. Обратитесь к объектам, вызовите метод(ы). Когда здесь вызываются конструкторы? 
    Запишите состояние объектов в файл, загрузить из файла.
